Vagrant.configure("2") do |config|

  config.vm.define "bionic64-postgresql-13.2-source" do |source|
    source.vm.box = "ubuntu/bionic64"
    source.vm.hostname = "bionic-postgres-13-2-source"
    source.vm.provision "shell", path: "install-timescaledb.sh", args: "--postgresql_version 13.2"
  end

  config.vm.define "bionic64-postgresql-13-package" do |package|
    package.vm.box = "ubuntu/bionic64"
    package.vm.hostname = "bionic-postgres-13-package"
    package.vm.provision "shell", inline:<<-SHELL
    sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    sudo apt-get update
    sudo apt-get -y install postgresql-13
    SHELL
  end

end
